"""
https://www.aig.sg/home
https://www.aig.sg/home/solutions/personal 
https://www.aig.sg/home/solutions/personal/accident-and-health 
https://www.aig.sg/home/solutions/personal/car-insurance?plan=2&dc=Y 
https://www.aig.sg/home/solutions/personal/home-insurance 
https://www.aig.sg/home/solutions/personal/travel-guard?dc=Y 
https://www.aig.sg/personal/pay-quote/retrieve?utm_source=home-page-your-policy&utm_medium=website-main&utm_campaign=topnav
https://www.aig.sg/home/solutions/business-products-and-services/accident-and-health 
https://www.aig.sg/home/solutions/business-products-and-services/casualty
https://www.aig.sg/home/solutions/business-products-and-services/commercial-motor
https://www.aig.sg/home/solutions/business-products-and-services/energy-and-construction 
https://www.aig.sg/home/solutions/business-products-and-services/foreign-worker-bond 
https://www.aig.sg/home/solutions/business-products-and-services/fronting-and-captive-services 
https://www.aig.sg/home/solutions/business-products-and-services/marine
https://www.aig.sg/home/solutions/business-products-and-services/multinational-solutions 
https://www.aig.sg/home/solutions/business-products-and-services/political-risk 
https://www.aig.sg/home/solutions/business-products-and-services/property
https://www.aig.sg/home/solutions/business-products-and-services/sme-business-insurance 
https://www.aig.sg/home/claims/personal-claims 
https://www.aig.sg/home/claims/business-claims 
"""
