"""
https://www.chubb.com/sg-en/
https://www.chubb.com/sg-en/claims.html
https://www.chubb.com/sg-en/business/financial-lines.html 
https://www.chubb.com/sg-en/business/marine.html 
https://www.chubb.com/sg-en/business/property.html 
https://www.chubb.com/sg-en/business/global-health-safety-environmental-services.html 
https://www.chubb.com/sg-en/business/industry-practices.html 
https://www.chubb.com/sg-en/business/risk-engineering-services.html
https://www.chubb.com/sg-en/business/transportation-risk-management.html 
https://www.chubb.com/sg-en/individuals-families/travel-protection.html 
https://www.chubb.com/sg-en/individuals-families/home-insurance.html
https://www.chubb.com/sg-en/individuals-families/jewellery-and-watch-cover.html 
https://www.chubb.com/sg-en/individuals-families/personal-accident-insurance.html 
https://www.chubb.com/sg-en/individuals-families/hospital-income-insurance.html 
https://www.chubb.com/sg-en/individuals-families/mobile-phone-insurance.html 
https://www.chubb.com/sg-en/individuals-families/dental-insurance.html
https://www.chubb.com/sg-en/business/accident-health.html 
https://www.chubb.com/sg-en/business/casualty.html 
https://www.chubb.com/sg-en/business/construction.html
https://www.chubb.com/sg-en/business/cyber.html
https://www.chubb.com/sg-en/business/energy.html 
https://www.chubb.com/sg-en/business/environmental.html
"""