"""
https://www.etiqa.com.sg/ 
https://www.etiqa.com.sg/personal/life-critical-illness-protection/ 
https://www.etiqa.com.sg/personal/premier-solutions/ 
https://www.etiqa.com.sg/personal/investments/ 
https://www.etiqa.com.sg/personal/savings-retirement/ 
https://www.etiqa.com.sg/personal/personal-accident/ 
https://www.etiqa.com.sg/personal/personal-cyber-insurance/ 
https://www.etiqa.com.sg/personal/maid-insurance/ 
https://www.etiqa.com.sg/personal/travel-insurance/ 
https://www.etiqa.com.sg/personal/home-insurance/ 
https://www.etiqa.com.sg/personal/fire-insurance/ 
https://www.etiqa.com.sg/personal/pet-insurance/ 
https://www.etiqa.com.sg/personal/motor-insurance/
https://www.etiqa.com.sg/business-insurance/accident-health/ 
https://www.etiqa.com.sg/business-insurance/commercial-vehicle/ 
https://www.etiqa.com.sg/business-insurance/casualty/ 
https://www.etiqa.com.sg/business-insurance/corporate-travel/ 
https://www.etiqa.com.sg/business-insurance/engineering/ 
https://www.etiqa.com.sg/business-insurance/marine/ 
https://www.etiqa.com.sg/business-insurance/business-owners-super-suite/ 
https://www.etiqa.com.sg/business-insurance/miscellaneous/ 
https://www.etiqa.com.sg/business-insurance/property/ 
https://www.etiqa.com.sg/claims-and-services/
"""
