"""
https://www.lonpac.com/ 
https://www.lonpac.com/business-insurance/miscellaneous 
https://www.lonpac.com/business-insurance/marine 
https://www.lonpac.com/business-insurance/trade-credit 
https://www.lonpac.com/business-insurance/liability 
https://www.lonpac.com/business-insurance/insurance-packages 
https://www.lonpac.com/business-insurance/employee-benefits 
https://www.lonpac.com/business-insurance/engineering-machinery
https://www.lonpac.com/business-insurance/foreign-workers 
https://www.lonpac.com/business-insurance/bond/performance-tender-advance-payment 
https://www.lonpac.com/claims 
https://www.lonpac.com/business-insurance/property 
https://www.lonpac.com/business-insurance/motor/commercial-vehicle
https://www.lonpac.com/personal-insurance/motor/private-car-secure-third-party-fire-theft 
https://www.lonpac.com/personal-insurance/travel/travel-secure
https://www.lonpac.com/personal-insurance/personal-accident/secure-protector 
https://www.lonpac.com/personal-insurance/personal-accident/flexicare-pa 
https://www.lonpac.com/personal-insurance/personal-accident/domestic-servant 
https://www.lonpac.com/personal-insurance/health/medisecure 
https://www.lonpac.com/personal-insurance/health/medisecure-centurial
https://www.lonpac.com/personal-insurance/health/medisecure-plus-2015
https://www.lonpac.com/personal-insurance/health/medisecure-booster 
https://www.lonpac.com/personal-insurance/health/secure-cancer-care 
https://www.lonpac.com/personal-insurance/home/houseowner-householder 
https://www.lonpac.com/personal-insurance/home/home-secure-plus
https://www.lonpac.com/business-insurance/property/fire 
https://www.lonpac.com/personal-insurance/online-insurance/motor-ezsecure-comprehensive 
https://www.lonpac.com/personal-insurance/online-insurance/motorcycle-insurance-comprehensive 
https://www.lonpac.com/personal-insurance/online-insurance/motorcycle-insurance-third-party 
https://www.lonpac.com/personal-insurance/online-insurance/travel-ezsecure 
https://www.lonpac.com/personal-insurance/motor/private-car-secure-comprehensive 
"""
